# Uncomment the next line to define a global platform for your project
platform :ios, '13.3'

target 'FireMessage' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FireMessage
  pod 'MessageKit'
  pod 'Firebase/Core'
  pod 'Firebase/Database'

end
